import React,{useState} from 'react'
import {cad} from './data'
import {sourceOptions,validateSource,summarizeSources} from './sources-model'

export function SourcePicker({data,setData,value,onChange,disabled,personal=false}){
 const [adding,setAdding]=useState(false),[name,setName]=useState(''),[error,setError]=useState('')
 const add=()=>{const clean=name.trim().replace(/\s+/g,' ');const issue=validateSource(clean,data.sources||[]);if(issue){setError(issue);return}const source={id:crypto.randomUUID(),name:clean};setData(d=>({...d,sources:[...(d.sources||[]),source]}));onChange(source.id);setAdding(false);setName('');setError('')}
 return <div className="source-picker"><label className="field"><span>Sourced from</span><select disabled={disabled} value={value} onChange={e=>onChange(e.target.value)}>{sourceOptions(data).filter(s=>personal||s.id!=='personal').map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select><small>Choose a branch separately if you want to compare locations.</small></label>{!adding?<button className="btn text" type="button" disabled={disabled} onClick={()=>setAdding(true)}>Add a store or source</button>:<div className="source-add"><label className="field"><span>New source name</span><input maxLength={70} value={name} onChange={e=>{setName(e.target.value);setError('')}} placeholder="Store and location"/></label><div className="button-row"><button className="btn" type="button" disabled={disabled} onClick={add}>Add source</button><button className="btn text" type="button" onClick={()=>{setAdding(false);setError('')}}>Cancel</button></div>{error&&<p className="error" role="alert">{error}</p>}</div>}</div>
}
function SourceRename({source,data,setData,disabled}){
 const [name,setName]=useState(source.name),[error,setError]=useState('')
 const save=()=>{const clean=name.trim().replace(/\s+/g,' ');const issue=validateSource(clean,data.sources||[],source.id);if(issue){setError(issue);return}setData(d=>({...d,sources:d.sources.map(s=>s.id===source.id?{...s,name:clean}:s)}));setError('Saved. All linked items use this name.')}
 return <div className="source-edit"><label className="field"><span>Source name</span><input aria-label={`Rename ${source.name}`} value={name} maxLength={70} disabled={disabled} onChange={e=>{setName(e.target.value);setError('')}}/></label><button className="btn" disabled={disabled||name===source.name} type="button" onClick={save}>Save name</button>{error&&<p className="fine" role="status">{error}</p>}</div>
}
export function SourceManager({data,setData,disabled}){
 const [value,setValue]=useState('unknown')
 return <details className="source-manager"><summary>Manage stores and sources</summary><p className="fine">Rename a source here to update every linked item. Personal wardrobe and Not recorded are fixed options.</p>{(data.sources||[]).map(s=><SourceRename key={s.id} source={s} data={data} setData={setData} disabled={disabled}/>)}<SourcePicker data={data} setData={setData} value={value} onChange={setValue} disabled={disabled}/></details>
}
export function SourceReport({data}){
 const rows=summarizeSources(data)
 return <section className="source-report"><div className="section-line"><h2>Which sources work for you?</h2></div><p>All recorded finds, grouped by where you got them.</p><p className="fine">Sales count paid pieces, excluding restocked returns. Profit is after refunds, item costs, preparation and postage, before shared business expenses. Unpaid reservations do not count as sales.</p>{rows.length?rows.map(r=><article className="source-result" key={r.id}><h3>{r.name}</h3><dl><div><dt>Finds</dt><dd>{r.finds}</dd></div><div><dt>Paid pieces</dt><dd>{r.sales}</dd></div><div><dt>Unsold pieces</dt><dd>{r.unsold}</dd></div><div><dt>Sales received, net</dt><dd>{cad(r.revenue)}</dd></div><div><dt>Profit before overhead</dt><dd>{r.profit===null?'Cost missing':cad(r.profit)}</dd></div><div><dt>Unsold stock at cost</dt><dd>{cad(r.stock)}{r.unknownStock>0?' + unknown':''}</dd></div></dl>{r.unknownSales>0&&<p className="fine">{r.unknownSales} paid piece(s) have no confirmed cost. Profit is incomplete.</p>}{r.unknownStock>0&&<p className="fine">{r.unknownStock} unsold piece(s) need a cost or confirmed transfer value.</p>}</article>):<p>Add a find and choose its source to start comparing.</p>}<p className="fine">Sample data only. Bundle payments, delivery fees, refunds and postage are split by item asking price, equally when all prices are zero. Store comparisons exclude shared expenses. Returned stock follows the prototype’s whole-order restock setting.</p></section>
}
